### ISSUE TITLE
OpenRISC Clock Handler Frequency

### ISSUE THREAD

**Issue by gbesnard** [nanvix/nanvix#237]
**Description**

Currently, the or1k clock handler routine `do_clock()` doesn't seem to be called regularly.

**Observation**
- `do_clock` is called infrequently (usually by burst) and not often (even though no other process than _idle_ and _init_ exists).
- `do_clock` is called so few that preemptive `yield` by concurrent threads of execution does not happen (or one should wait a very long time).

**Hypothesis**
1. "by doing some random breakpoints in GDB (with Ctrl+C), I noticed something interesting: the kernel always stops at one of these 3 points: dtlb_miss_handler, itlb_miss_handler, and tlb_flush." - @Theldus

**Solutions ?**
1.  perform the TLB flush only on the required portions and not on the whole ?

**Comment by Theldus** [comment]
This issue was fixed in commits 2bc4d9ff6cb849ab5ffd647f4782002caf572160 and db010e65ec017a0c048d28625fbe63f7e70c3df0, so by now the `do_clock()` function is called regularly and the 'test thread' can be executed and finished.

The selective TLB flush proposed above can be considered an enhancement and would fit better into a separate issue.
